### PR TITLE
Add WHATWG-themed CSS for nginx directory listings

### PR DESCRIPTION
**Pull request by sideshowbarker**
Fixes https://github.com/whatwg/whatwg.org/issues/91

### CODE REVIEW

**Comment by annevk** [comment]
I guess that means we first need to add that resource? (If you just put it there it won't work as we use rsync.)

**Comment by sideshowbarker** [comment]
> I guess that means we first need to add that resource? (If you just put it there it won't work as we use rsync.)

Yeah I know, am working on a separate PR for that now

**Comment by sideshowbarker** [comment]
> According to https://github.com/aperezdc/ngx-fancyindex/blob/master/README.rst#fancyindex-css-href this doesn't replace any built-in styles so we'd end up loading two stylesheets just directory listing. Not exactly ideal, but I guess acceptable? We'll have to make sure my suggestion ends up overwriting the defaults though.

The description there says:

> The link is inserted after the built-in CSS rules, so you can override the default styles.

So that seems to make it clear that styles in the default stylesheet definitely get overridden by any corresponding styles in the stylesheet specified as the `fancyindex_css_href` value.

> …we'd end up loading two stylesheets… Not exactly ideal, but I guess acceptable?

I don’t know that we have any alternative — well, other than hacking the installed `ngx-fancyindex` sources in the server environment to replace the defaults. Because as far as I can see, it doesn’t expose any way to programatically replace the defaults — instead it only lets you specify an additional stylesheet to override them.

**Comment by annevk** [comment]
It seems the builtin style sheet is `<style>` so it's not too bad, but I filed https://github.com/aperezdc/ngx-fancyindex/issues/79 anyway in the hopes of improving this at some future point.

**Pull request merged**
