### PR TITLE
Use a package.json for test dependency (node-fetch)

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
I have a feeling this won't be quite what you wanted, but PTAL :)

**Comment by domenic** [comment]
This is quite reasonable. It just makes it easy to edit the conventional location for adding dependencies instead of editing a bash script.

You can also add other fields (like name/description/private) but it appears with later npm versions you no longer get a warning when omitting them, so they're not necessary.

For an analogue see https://github.com/whatwg/streams/blob/master/package.json . (devDependencies vs. dependencies isn't really material in these kind of cases; I think dependencies is probably better, actually.)

**Comment by foolip** [comment]
There are actually warnings, but it doesn't fail. I copied this from https://github.com/foolip/day-to-day/blob/master/package.json, where I didn't care about creating a package or anything. Do you think it's OK to not have a version but just *? My thinking was that if the latest version breaks something, it's just as well if it breaks right away, and we can pin it only if necessary.

**Comment by domenic** [comment]
I prefer known-good versions so we can isolate failure cases. E.g. they could just completely change their API with what you have now. Using the default (in this case I believe it'd be `"^1.7.3"`, i.e. anything in the `1.x` range >= 1.7.3) would be good.

**Comment by foolip** [comment]
I'll go with "^1.7.3" then.

**Pull request merged**
