### PR TITLE
Configure lists.whatwg.org to redirect

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
This shouldn't be merged yet but is ready for review. See https://github.com/whatwg/whatwg.org/pull/269 first.

**Comment by annevk** [comment]
So the idea here is that we'd require a second click before you end up at the final destination?

**Comment by foolip** [comment]
Yes, because we don't know which URLs are actually archived, and it's probably useful for people to learn what has happened to the lists if they follow old links. We could replace links where we find them to point directly at public-whatwg-archive or web.archive.org though.

**Comment by annevk** [comment]
Sounds good. I think we're also happy to take PRs for 301 redirects that go directly from lists.whatwg.org to lists.w3.org. I've been thinking of doing that at least for the all the URLs mentioned at some point in the HTML Standard source and perhaps also the sources of other standards, but haven't made the time thus far.

**Comment by foolip** [comment]
I'll close this PR because it's not what I'd like to land. I'm working on a static copy of what can be easily restored, and maybe we can have a fancy 404 handler that explains how to find things that are still missing.

**Pull request closed without merging**
