### PR TITLE
Redirect away from trailing dot domains

### PR DESCRIPTION
**Pull request by annevk**
Fixes https://github.com/whatwg/whatwg.org/issues/100.

### CODE REVIEW

**Comment by annevk** [comment]
Not a 100% this is correct. It seems it would be nice to share Nginx configuration across servers.

**Comment by annevk** [comment]
Found #62 while looking around for other inconsistencies.

**Comment by annevk** [comment]
(Nginx code found at https://stackoverflow.com/questions/15452328/nginx-redirect-domain-trailing-dot by the way.)

**Comment by foolip** [comment]
Is it important that we do this kind of normalization? https://whatwg.org.//faq? has pointless double slashes and a trailing ? that are pretty harmless and seem similar to this case.

**Comment by annevk** [comment]
Not sure. I somewhat dislike your example not returning a 404. It seems good to redirect the trailing dot variant similar to how we redirect the www. variant, but I guess we could also leave it.

**Comment by foolip** [comment]
@annevk, what do you think we should do with this? More config makes for more work if we migrate server  setup again, but I'm OK with this if you hate trailing dots :)

**Comment by annevk** [comment]
I'll close it for now.

**Pull request closed without merging**
