### PR TITLE
Use a certbot renewal hook to reload nginx on new cert

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
I got rid of the solution I used on marquee before and tried to make something that will work on both.

I've run the 01-certbot script on both marquee and noembed and checked that /etc/letsencrypt/renewal-hooks/deploy/nginx was created, and then executed it on noembed to make sure it reloaded.

But... running `sudo certbot renew --force-renewal` on marquee didn't result in the new cert being used, so something is still wrong here.

**Comment by foolip** [comment]
OK... the mechanism I'm trying to use was added in https://github.com/certbot/certbot/commit/356471cdf6df1d277c9f013a3595dba20ac02f6c which was released in certbot 0.19, and we're still using 0.10.

**Comment by foolip** [comment]
So, we can get a recent enough certbot using `apt -t stretch-backports install certbot`, after uncommenting backports in /etc/apt/sources.list. I'm happy to try that, but there is some risk that it'll break things, and then downgrading could be tricky. And making that config reproducible from our scripts is some additional work too.

@domenic, thoughts before I break everything? :)

**Comment by domenic** [comment]
It seems relatively important to have a recent version of certbot, and also to have the config for installing that version checked in here. So, seems like a good idea to proceed, I suppose?

**Comment by foolip** [comment]
I've pushed a commit which uses `apt -t stretch-backports install certbot` and tried on both marquee and noembed. Running `certbot renew --force-renewal`, I saw "Running deploy-hook command: /etc/letsencrypt/renewal-hooks/deploy/nginx" in the output and the certs sent to the browser were updated.

So, this seems to work now. @sideshowbarker, I take it you reviewed that commit, so I'll go ahead and merge.

Note that the setup for multicol (blog and wiki) was *not* updated, and its configuration isn't checked in at all. That's a problem, but it renewal already works there using Apache, so I'm going to leave it alone.

**Pull request merged**
