### PR TITLE
Add tests to notice if the wiki is broken

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by GPHemsley** [comment]
Are we sure these particular checks are reliable?

When the database goes down, we get a static page (possible from cache?) that says something about technical difficulties. Pages that are supposed to be dynamically generated (like History) will look nothing like they normally do.

**Comment by foolip** [comment]
It was the history page that was broken, and when it was it looked just like the page itself, so this test would have failed. If there are other ways that history can fail, then more tests would be in order. Do you have something rule that I can write a test by?

**Comment by GPHemsley** [comment]
It's more than just the history page that has trouble. Every page looks different than it's supposed to.

Let me kill the database to get it to generate the actual error again.

**Comment by GPHemsley** [comment]
The page will show this error at the bottom:

```
<h1>Sorry! This site is experiencing technical difficulties.</h1><p>Try waiting a few minutes and reloading.</p><p><small>(Cannot contact the database server)</small></p>
```

In addition, various URLs (mostly scripts, it seems), including the page itself, will return a special 500 error:

```
Status: 500 MediaWiki exception
```

**Comment by foolip** [comment]
OK, I've added tests that should fail if either of those two things happen.

**Comment by foolip** [comment]
@GPHemsley, does that look good to you now?

**Comment by foolip** [comment]
Well, these are just tests, and I'm trying to get some failing tests in https://travis-ci.org/whatwg/misc-server/builds/298241329 passing, so I'll just merge this and work on getting everything passing.

**Comment by GPHemsley** [comment]
LGTM

**Comment by foolip** [comment]
Thanks for reviewing!

**Pull request merged**
