### PR TITLE
Ensure CSS & SVG resources are served with charset

### PR DESCRIPTION
**Pull request by sideshowbarker**

### CODE REVIEW

**Comment by sideshowbarker** [comment]
Two cases where without this change, some resources are served without `charset=utf-8`:

* https://resources.whatwg.org/standard.css
* https://resources.whatwg.org/logo-fetch.svg

**Comment by domenic** [comment]
I thought SVG and CSS were always interpreted as UTF-8?

**Comment by annevk** [comment]
XML should be (if there's nothing else), but CSS falls back to whatever the document that embeds it uses (which is kinda bad for optimized caches, I wonder if implementations have bugs there).

**Comment by domenic** [comment]
Ah right. But all our documents are UTF-8 :).

I don't see the harm in merging this, but don't see the gain either. *Shrug* Mostly just made the above comment to educate myself. Happy to leave the decision to folks more involved with the server side.

**Comment by sideshowbarker** [comment]
> I thought SVG and CSS were always interpreted as UTF-8?

Good point — I actually hadn’t thought about it from the perspective. I had just noticed that our web server wasn’t sending a charset for our SVG and CSS resources, though it does for our HTML and JavaScript resources.

> I don't see the harm in merging this, but don't see the gain either.

I think you’re right. If the change isn’t necessary then I think we shouldn’t merge it. So I’ll go ahead and close this.

**Comment by annevk** [comment]
The CSS change might be somewhat useful when viewing CSS directly, though arguably that's also a UA bug if they don't fallback to UTF-8 there, so maybe best to leave it.

**Pull request closed without merging**
